#' Calculate Area under the PR curve (AUPR).
#'
#' The area under the precision-recall curve (AUPRC) is a metric that is used
#' to evaluate the performance of a binary classification model. It is
#' calculated by measuring the area under the curve generated by plotting
#' the precision and recall of a model as functions of a probability threshold.
#'
#' @details
#' Precision and recall are two metrics that are commonly used to evaluate
#' the performance of a binary classification model. Precision is the ratio of
#' true positive predictions to the total number of positive predictions made
#' by the model, while recall is the ratio of true positive predictions to
#' the total number of actual positive samples.
#'
#' The AUPRC is calculated by first generating a series of precision-recall
#' pairs at different probability thresholds. This is done by varying the
#' threshold used to classify a sample as positive or negative, and calculating
#' the precision and recall at each threshold. These precision-recall pairs
#' are then plotted on a graph, with precision on the y-axis and recall on the
#' x-axis. The AUPRC is then calculated by measuring the area under this curve.
#'
#' The AUPRC is a useful metric because it allows for a more comprehensive
#' evaluation of a model's performance. Unlike the F1-score, which is a
#' single number that represents the harmonic mean of precision and recall,
#' the AUPRC takes into account the entire precision-recall curve and provides
#' a more complete picture of a model's performance.
#'
#' @param ... `r rox("dots")`
#'
#' @export
#'
calc_aupr <- function(...) UseMethod("calc_aupr")



#' @describeIn calc_aupr
#'
#' @param tp `r rox("tp")`
#' @param fp `r rox("fp")`
#' @param fn `r rox("fn")`
#'
#' @export
#'
calc_aupr.default <- function(tp, fp, fn, ...) {

  ppv <- calc_precision(tp, fp, FALSE, 0)[1]
  tpr <- calc_tpr(tp, fn, FALSE, 0)[1]

  (ppv + tpr) / 2

}



#' @describeIn calc_aupr
#'
#' @param tbl `r rox("tbl")`
#'
#' @export
#'
calc_aupr.table <- function(tbl, ...) {

  tp <- tbl[2,2]
  fp <- tbl[2,1]
  fn <- tbl[1,2]

  calc_aupr(tp, fp, fn)

}



#' @describeIn calc_aupr
#'
#' @param data `r rox("data")`
#' @param prediction `r rox("prediction")`
#' @param reference `r rox("reference")`
#'
#' @export
#'
calc_aupr.data.frame <- function(
    data,
    prediction, reference, ...
) {

  data <- data[, c(prediction, reference)]
  tbl <- table(data)

  calc_aupr(tbl)

}
