#' Calculate Area under the ROC curve for each class (auroc).
#'
#' The area under the curve (AUC) is a metric that is used to evaluate the
#' performance of a binary classification model. It is calculated by measuring
#' the area under the curve generated by plotting the true positive rate (TPR)
#' and false positive rate (FPR) as functions of a probability threshold.
#'
#' @details
#' The TPR and FPR are two metrics that are commonly used to evaluate the
#' performance of a binary classification model. The TPR is the ratio of true
#' positive predictions to the total number of actual positive samples, while
#' the FPR is the ratio of false positive predictions to the total number of
#' actual negative samples.
#'
#' The AUC can be calculated by first generating a series of TPR-FPR pairs at
#' different probability thresholds. This is done by varying the threshold used
#' to classify a sample as positive or negative, and calculating the TPR and
#' FPR at each threshold. These pairs are then plotted on a graph, with the
#' TPR on the y-axis and the FPR on the x-axis. The AUC is then calculated
#' by measuring the area under this curve.
#'
#' The AUC is a useful metric because it allows for a more comprehensive
#' evaluation of a model's performance. The AUC takes into account the entire
#' TPR-FPR curve and thereby provides a more complete picture of a model's
#' performance.
#'
#' @seealso [calc_tpr()]
#' @seealso [calc_fpr()]
#' @seealso [calc_aupr()]
#'
#' @param ... `r rox("dots")`
#'
#' @export
#'
calc_auroc <- function(...) UseMethod("calc_auroc")



#' @describeIn calc_auroc
#'
#' @param tn `r rox("tn")`
#' @param fp `r rox("fp")`
#' @param tp `r rox("tp")`
#' @param fn `r rox("fn")`
#'
#' @export
#'
calc_auroc.default <- function(tn, fp, tp, fn, ...) {

  tnr <- calc_tnr(tn, fp, F, 0)[1]
  tpr <- calc_tpr(tp, fn, F, 0)[1]

  (tnr + tpr) / 2

}



#' @describeIn calc_auroc
#'
#' @param tbl `r rox("tbl")`
#'
#' @export
#'
calc_auroc.table <- function(tbl, ...) {

  tp <- tbl[2,2]
  tn <- tbl[1,1]
  fp <- tbl[2,1]
  fn <- tbl[1,2]

  calc_auroc(tn, fp, tp, fn)

}



#' @describeIn calc_auroc
#'
#' @param data `r rox("data")`
#' @param prediction `r rox("prediction")`
#' @param reference `r rox("reference")`
#'
#' @export
#'
calc_auroc.data.frame <- function(
    data,
    prediction, reference, ...
) {

  data <- data[, c(prediction, reference)]
  tbl <- table(data)

  calc_auroc(tbl)

}

