#' Calculate Area under the PR curve (AUPR).
#'
#' The area under the precision-recall curve (AUPRC) is a metric that is used
#' to evaluate the performance of a binary classification model. It is
#' calculated by measuring the area under the curve generated by plotting
#' the precision and recall of a model as functions of a probability threshold.
#'
#' @details
#' Precision and recall are two metrics that are commonly used to evaluate
#' the performance of a binary classification model. Precision is the ratio of
#' true positive predictions to the total number of positive predictions made
#' by the model, while recall is the ratio of true positive predictions to
#' the total number of actual positive samples.
#'
#' The AUPRC is calculated by first generating a series of precision-recall
#' pairs at different probability thresholds. This is done by varying the
#' threshold used to classify a sample as positive or negative, and calculating
#' the precision and recall at each threshold. These precision-recall pairs
#' are then plotted on a graph, with precision on the y-axis and recall on the
#' x-axis. The AUPRC is then calculated by measuring the area under this curve.
#'
#' @param ... `r rox("dots")`
#'
#' @examples
#' # Create a sample data frame with prediction and reference columns
#' data <- data.frame(
#'   prediction = c(0.9, 0.8, 0.6, 0.5, 0.3, 0.2, 0.1),
#'   reference = c(1, 0, 0, 1, 1, 0, 1)
#' )
#'
#' # Calculate AUPR using the data frame method
#' calc_aupr(data, prediction = "prediction", reference = "reference")
#'
#' # the table method
#' calc_aupr(table(data$prediction, data$reference))
#'
#' # Calculate AUPR using the default method
#' tp <- 2
#' fp <- 1
#' fn <- 2
#' calc_aupr(tp, fp, fn)
#'
#' @seealso [calc_precision()]
#' @seealso [calc_tpr()]
#' @seealso [calc_auroc()]
#'
#' @export
#'
calc_aupr <- function(...) UseMethod("calc_aupr")



#' @describeIn calc_aupr
#'
#' @param tp `r rox("tp")`
#' @param fp `r rox("fp")`
#' @param fn `r rox("fn")`
#'
#' @export
#'
calc_aupr.default <- function(tp, fp, fn, ...) {

  ppv <- calc_precision(tp, fp, FALSE, 0)[1]
  tpr <- calc_tpr(tp, fn, FALSE, 0)[1]

  (ppv + tpr) / 2

}



#' @describeIn calc_aupr
#'
#' @param tbl `r rox("tbl")`
#'
#' @export
#'
calc_aupr.table <- function(tbl, ...) {

  calc_aupr(tp = tbl[2,2], fp = tbl[2,1], fn = tbl[1,2])

}



#' @describeIn calc_aupr
#'
#' @param data `r rox("data")`
#' @param prediction `r rox("prediction")`
#' @param reference `r rox("reference")`
#'
#' @export
#'
calc_aupr.data.frame <- function(
    data,
    prediction, reference, ...
) {

  tbl <- table(data[, c(prediction, reference)])

  calc_aupr(tbl)

}
